apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-auth-app
  labels:
    app: react-auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-auth-app
  template:
    metadata:
      labels:
        app: react-auth-app
    spec:
      containers:
      - name: react-auth-app
        image: react-auth-app:latest
        imagePullPolicy: Never # Forces K8s to use the local image loaded into minikube
        ports:
        - containerPort: 80
