apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-auth-app
  labels:
    app: react-auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-auth-app
  template:
    metadata:
      labels:
        app: react-auth-app
    spec:
      containers:
      - name: react-auth-app
        image: iamvasu/react-auth-app2:latest # TODO: Replace iamvasu
        imagePullPolicy: Always
        ports:
        - containerPort: 80
