apiVersion: v1
kind: Service
metadata:
  name: react-auth-service
spec:
  type: NodePort
  selector:
    app: react-auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30030 # Optional: fixing the port makes it easier to access
